Models/real_estate.cs
namespace Недвижимость.Models
{
    public class real_estate
    {   
        public int id;
        public string name;
        public string description;
        public int price;       
        public string img;
        public string region;
        public string city;
        public string view; //вид
        public string area; //площадь
        public string comfort;
        public string fio;
        public string numberTelephone;
        public bool site_availability; //Наличие участка
    }
}

Models/real_estates.cs
namespace Недвижимость.Models
{
    public class real_estates
    {
     
        public List<real_estate> getHouses()
        {
            List<real_estate> listreal_estate = new List<real_estate>();

            real_estate t1 = new real_estate();
            t1.id= 1;
            t1.name = "ПРОДАЕТСЯ дом в Молодежном";
            t1.description = "В продаже дом в ,5 соток земли.В дом заведен газ,водопровод,есть сауна,все необходимое для проживания";
            t1.price = 1581678;
            t1.region = "Киевская";
            t1.city = "Киев";
            t1.view = "Дом";
            t1.area = "10c";
            t1.img = "https://assets.archon.pl/images/products/ma8b260050bff5/widok-1-projekt-dom-w-balsamowcach-15-g-7c5d5a22e505c93623215600d31da636__289.jpg";
            t1.comfort = "Подсобные помещения, Сауна, баня, Душевая кабина, Гостевой, летний дом, Гараж, Беседка, мангал, Забор, ограждение, Кондиционер";
            t1.fio = "Иванов Иван Ивановичь";
            t1.numberTelephone = "38 03974297238";
            t1.site_availability = true;

            listreal_estate.Add(t1);


            real_estate t2 = new real_estate();
            t2.img = "https://ireland.apollo.olxcdn.com/v1/files/y50bm2osphs7-UA/image;s=1000x700";
            t2.id = 2;
            t2.name = "Продам дом Гореничи, 128м2, 5.6соток, все ком. асфальт";
            t2.description = "Продам будинок в смт.Дашава Всі документи в наявності Можливий торг Пишіть в особисті повідомлення або телефонуйте за номерами: 06 * ********92 Надя 09 * ********85 Микола.";
            t2.price = 2905873;
            t2.region = "Киевская";
            t2.city = "Киев";
            t2.view = "Дом";
            t2.area = "10c";
            t2.comfort = "Забор, ограждение, Подогрев пола, Терраса";
            t2.fio = "Виктор Викторович Виктор";
            t2.numberTelephone = "380 39822 2939";
            t2.site_availability = true;

            listreal_estate.Add(t2);

            real_estate t3 = new real_estate();
            t3.img = "https://ireland.apollo.olxcdn.com/v1/files/gvyj38kfcc5d1-UA/image;s=1000x700";
            t3.id = 3;
            t3.name = "Продаж будинку, Софіївська Борщагівка, 90м2";
            t3.description = "Представитель Собственника. Продам Дом с участком 15 соток. с. Лютеж. 32 км от Киева. Собственный выход в лес. 200 метров от Киевского моря. 7 мин ходьбы до супермаркета. Рядом школа., детский сад. Асфальтная подъездная дорога. Дом 2 этажа общей площадью 213 кв.м.+подвал 48 кв.м. + гараж 36 кв.м. 5 комнат, 3 санузла. Качественный дорогой ремонт, мебель и техника. Фундамент - на монолитной бетонной плите. Стены из красного кирпича. Утепление– 100 мм минеральная вата. Эксклюзивный дизайн фасада дома. Кровля - из глинянной натуральной итальянской черепицы. Ливневая дренажная система с выводом поверхностных вод за пределы участка, итальянский автополив с накопительной ёмкостью 4куб.м. Водоснабжения и скважины глубиной 67 м. На участке беседка, гостевой туалет, водопад и искусственный водоем. Резервное энергопитание обеспечивается дизельным генератором 14 кВт С автоматическим включением. Отопление – два электрокотла мощностью 3 и 25кВт. Бойлер горячей воды – 300 л. Резервное отопление – твердотопливный котёл с теплоаккумулятором объемом 1000 л. Дизельный Генератор подключен к дому. В строительство вложено 750 тыс долларов. Цена 420000 у.е. Минимальное переоформления. БЕЗ КОМИССИИ.";
            t3.price = 2942656;
            t3.region = "Киевская";
            t3.city = "Киев";
            t3.view = "Дом";
            t3.area = "10c";
            t3.comfort = "нету";
            t3.fio = "Григорий Григор Григориевич";
            t3.numberTelephone = "380 56 5656 63";
            t3.site_availability = true;

            listreal_estate.Add(t3);

            return listreal_estate;
         
    }
        public List<real_estate> getKvartirs()
        {
            List<real_estate> listreal_estate = new List<real_estate>();

            real_estate t1 = new real_estate();
            t1.id = 4;
            t1.name = "Здам квартиру в центрі. Власник";
            t1.description = "Продам 1к квартиру, за адресою: Гатне, бульвар Приозерний, будинок 7. Розташована на 8-поверсі. Новий сучасний ремонт( нова техніка, нові італійські меблі) Від Власника без комісій! 06******77 Житловий комплекс «Озерний гай Гатне» – це гармонійне поєднання природного ландшафту і малоповерхової забудови, стриманого дизайну з максимальною функціональністю. Озера з лебедями та облаштовані пляжі – унікальна перлина комплексу. Уже зараз можна з комфортом відпочити на березі мальовничих озер, а влітку – позасмагати на зручних шезлонгах, прогулятися алеями, запросити друзів на барбекю у спеціально обладнаних дерев’яних альтанках і просто гарно проводити кожен день. А завдяки власній інфраструктурі мешканцям будуть доступні усі необхідні заклади для освіти, харчування, відпочинку та спорту. Тут ви будете дихати на повні груди, почуватися у цілковитій безпеці і при цьому насолоджуватися усіма перевагами сучасного життя за містом. Озерний гай Гатне - переходьте на ЕКО.";
            t1.price = 16000;
            t1.region = "Киевская";
            t1.city = "Киев";
            t1.view = "Квартира";
            t1.area = "10c";
            t1.img = "https://ireland.apollo.olxcdn.com/v1/files/0mnnxorp73ck3-UA/image;s=1000x700";
            t1.comfort = "Видеонаблюдение, Кондиционер, Балкон, лоджия, Ванна, Консъерж, Лифт, Пожарная сигнализация, Гостевой паркинг, Мебель на кухне, Панорамные окна, Охраняемая территория, Грузовой лифт, Сигнализация";
            t1.fio = "Назар Назарий Назаровичь";
            t1.numberTelephone = "38 03974297238";
            t1.site_availability = false;
            
            listreal_estate.Add(t1);


            real_estate t2 = new real_estate();
            t2.img = "https://ireland.apollo.olxcdn.com/v1/files/k9845lc9zlu42-UA/image;s=1000x700";
            t2.id = 5;
            t2.name = "Затишна однокімнатна квартира, БЕЗ КОМІСІЇ";
            t2.description = "Просторная 2к квартира, 62 кв. м., с выдовыми окнами на 3 озера. Светлая, уютную и чистую квартиру. Продажа со всей мебелью и техникой. Утром Восход солнца ;) вид бомбезный ;) Раздельные две комнаты. Большие окна, отличный вид, квартира выполненная в едином стиле, очень уютная. Место самое лучше, сразу через дорогу Епицентр, Метро, 9 минут до метро Позняки. Закрытая территория придомовая, консьержи, видеонаблюдение, очень хороший дом все ухожено и убрано, в доме ОСББ. Деревянная кровать, с ортопедическим матрасом двосезонным зима-лето. Счётчики на тепло, воду, электричество. Регуляторы на батареях. В квартире есть все: кондиционер, бойлер, холодильник, плита, микроволновка...";
            t2.price = 550000;
            t2.region = "Киевская";
            t2.city = "Киев";
            t2.view = "Квартира";
            t2.area = "10c";
            t2.comfort = " Балкон, лоджия, Ванна, Мебель на кухне, Парковочное место";
            t2.fio = "Игорь Игорович Игорь";
            t2.numberTelephone = "380 5654 4 74";
            t2.site_availability = false;

            listreal_estate.Add(t2);

            real_estate t3 = new real_estate();
            t3.img = "https://ireland.apollo.olxcdn.com/v1/files/9rgj7ea6ply53-UA/image;s=1000x700";
            t3.id = 6;
            t3.name = "Затишна однокімнатна квартира, БЕЗ КОМІСІЇ";
            t3.description = "Аренда шикарной 2к квартиры,по адресу Здолбуновская 13, можно с воспитанным животным небольшим.Редко выключают свет! -74/12 кухня м2 -Этаж 18/24 -Много места для хранения и шкафов Квартира укомплектована мебелью и техникой: Кухня -Холодильник -Духовой шкаф -Варочная панель -Встроенная кухня -Обеденный стол,стулья -Посудомоечная машина комната: -Шкаф -Диван -Телевизор комната вторая: -Шкаф -Кровать -Кондиционер В наличии стиральная машина Возле дома:школы,садики,магазины,трц,кафе,2 озера, парк .Прекрасная транспортная развязка, рядом 2 станции метро Позянки 15 мин птранспортом, Харьковская 20мин";
            t3.price = 2942656;
            t3.region = "Киевская";
            t3.city = "Киев";
            t3.view = "Квартира";
            t3.area = "10c";
            t3.comfort = "Балкон, лоджия, Ванна, Мебель на кухне, Парковочное место";
            t3.fio = "Григорий Григор Григориевич";
            t3.numberTelephone = "380 546 646";
            t3.site_availability = false;

            listreal_estate.Add(t3);

            return listreal_estate;

        }//переделать под квартиры
        public List<real_estate> getDachs()
        {
            List<real_estate> listreal_estate = new List<real_estate>();

            real_estate t1 = new real_estate();
            t1.id = 7;
            t1.name = "Дача с. Жирівка з деревяним будиночком";
            t1.description = "Дача с. Жирівка знаходиться в гарному з багатою зеленню місці. Деревяний будиночок, сад, електрика. Ділянка 4,5 сот. Терміново. Торг. Ціна 6500 $";
            t1.price = 238884;
            t1.region = "Киевская";
            t1.city = "Киев";
            t1.view = "Дача";
            t1.area = "10c";
            t1.img = "https://ireland.apollo.olxcdn.com/v1/files/8dz3v2ud09y83-UA/image;s=1000x700";
            t1.fio = "Игорь Игорь Игоровичь";
            t1.numberTelephone = "38 5464 64 456";
            t1.site_availability = true;

            listreal_estate.Add(t1);


            real_estate t2 = new real_estate();
            t2.img = "https://ireland.apollo.olxcdn.com/v1/files/iisyqojupfbz-UA/image;s=1000x700";
            t2.id = 8;
            t2.name = "Смежная двойная дача на 18 соток, 15 км. от города с питьевой водой";

Controllers/Real_estateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Недвижимость.Models;

namespace Недвижимость.Controllers
{
    public class Real_estateController : Controller
    {
        real_estates real_Estates = new real_estates();


        public IActionResult Home()
        {
            List<real_estate> listRealEstate = real_Estates.getHouses();
            return View("RealEstate", listRealEstate);  
        }
        public IActionResult Kvartira()
        {
            List<real_estate> listRealEstate = real_Estates.getKvartirs();
            return View("RealEstate", listRealEstate);
        }
        public IActionResult Dacha()
        {
            List<real_estate> listRealEstate = real_Estates.getDachs();
            return View("RealEstate", listRealEstate);
        }
        public IActionResult Garaji()
        {
            List<real_estate> listRealEstate = real_Estates.getGarajs();
            return View("RealEstate", listRealEstate);

        }

        [Authorize]
        public IActionResult AddNewAdvt()
        {
            return View();
        }
        public void AddNewEstate(string name, string description, string price, string region, string view, string area, string comfort, bool site_availability)
        {

        }

        public IActionResult aboutTovar(int id) {


            foreach(var a in real_Estates.getHouses())
            {
                if(a.id==id)
                {
                    return View(a);
                }
            }
            foreach (var a in real_Estates.getKvartirs())
            {
                if (a.id == id)
                {
                    return View(a); 
                }
            }

            foreach (var a in real_Estates.getDachs())
            {
                if (a.id == id)
                {
                    return View(a);
                }
            }
            foreach (var a in real_Estates.getGarajs())
            {
                if (a.id == id)
                { 
                    return View(a); 
                }
            }

            return null;

        }
    }
}

Views/Real_estate/AddNewAdvt.cshtml
<form asp-controller="Real_estate" asp-action="AddNewEstate">
    <select>
        <option value="0">Тип объявления</option>
        <option value="1">дома</option>
        <option value="2">квартиры</option>
        <option value="3">дачи</option>
        <option value="4">гаражи</option>

    </select>
    <label>Название</label>
    <input name="name" type="text" placeholder="Название" />
    <br />

    <label>Описание</label>
    <input name="description" type="text" placeholder="Описание" />
    <br />
    <label>Цена</label>
    <input name="price" type="number" placeholder="Цена"/>
    <br />
    <label>Изображения</label>
    <input name="img" type="file" placeholder="Изображения" />
    <br />
    <label>Регион</label>
    <input name="region" type="text" placeholder="Регион" />
    <br />
    <label>Вид</label>
    <input name="view" type="text" placeholder="Вид" />
    <br />
    <label>Площадь</label>
    <input name="area" type="text" placeholder="Площадь" />
    <br />
    <label>Комфорт</label>
    <input name="comfort" type="text" placeholder="Комфорт" />
    <br />
    <label>Наличие участка</label>
    <input name="site_availability" type="checkbox" placeholder="Наличие участка" />
    <br />
   
    <input type="submit" value="создать" />


</form>


     public int id;
        public string name;
        public string description;
        public int price;
        public string img;
        public string region;
        public string city;
        public string view; //вид
        public string area; //площадь
        public string comfort;
        public string fio;
        public string numberTelephone;
        public bool site_availability; //Наличие участка

Views/Real_estate/RealEstate.cshtml
@{
	for(int i = 0; i < Model.Count; i++)
	{


        <a href="~/Real_estate/aboutTovar?id=@Model[i].id" class="RealEstateFirstDiv">
        <div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
    <img width="100%" height="70%" src="@Model[i].img"> 
    </div>
     <div class="col-md-8">
      <div class="RealEstateName"> @Model[i].name  </div>
       
        <div class="RealEstatePrice">@Model[i].price грн</div>
        <div class="RealEstateRegion">Область: @Model[i].region</div>
        <br>
         <div class="RealEstateRegionArea">Площадь: @Model[i].area</div>
        </div>
    </div>
  </div>
  
     </a>
   
  


	}
}



@* public string name;
        public string description;
        public int price;
     
        public string img;
        public string region;
        public string сity;
        public string view; //вид
        public string area; //площадь
        public string comfort;
        public string fio;
        public string numberTelephone;
        public bool site_availability; //Наличие участка*@

Views/Real_estate/aboutTovar.cshtml
@{
	<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">

       <img width="100%" src="@Model.img">  
    </div>
     <div class="col-md-8">
      <div class="RealEstateAbouteTovarSecondBlock">
            <div class="RealEstateAbouteTovarName"> @Model.name  </div>
       
        <div class="RealEstateAbouteTovarPrice">@Model.price грн</div>
        <div class="RealEstateAbouteTovarRegion">Область: @Model.region</div>
      <div class="RealEstateAbouteTovarCity">
        Город: @Model.city
      </div>
        <br>
         <div class="RealEstateAbouteTovarArea">Площадь: @Model.area</div>
        <div class="RealEstateAbouteTovarView">
        Недвижимость: @Model.view
      </div>
      <div class="RealEstateAbouteTovarFio">
        @Model.fio
      </div>
      <div class="RealEstateAbouteTovarComfort">
        Комфорт: @Model.comfort
      </div>
      <div class="RealEstateAbouteTovarDescription">
        Описание: @Model.description
      </div>
        </div>
    </div>
  </div>
  
    
   
  
</div>

     
       
      
       

	
}



@* public string name;
        public string description;
        public int price;
     
        public string img;
        public string region;
        public string сity;
        public string view; //вид
        public string area; //площадь
        public string comfort;
        public string fio;
        public string numberTelephone;
        public bool site_availability; //Наличие участка*@